### ISSUE TITLE
还在做安卓吗？

### ISSUE THREAD

**Issue by BZyanshui** [gavinliu/SimilarPhoto#1]

**Comment by viviant1224** [comment]
android Q上面运行会有问题

**Comment by gavinliu** [comment]
> android Q上面运行会有问题

算法核心在 https://github.com/gavinliu/SimilarPhoto/blob/master/app/src/main/java/cn/gavinliu/similar/photo/SimilarPhoto.java 这个类，可以自己拔出来用哈
